// Mocks generated by Mockito 5.4.4 from annotations
// in cloudy/test/app/features/home/domain/usecase/get_forecast_weather_uc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloudy/app/features/home/data/repositories/weather_repository_impl.dart'
    as _i3;
import 'package:cloudy/app/features/home/domain/entities/weather_entity.dart'
    as _i5;
import 'package:cloudy/app/features/select_area/domain/entities/area_entity.dart'
    as _i6;
import 'package:cloudy/core/state/data_state.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepositoryImpl extends _i1.Mock
    implements _i3.WeatherRepositoryImpl {
  @override
  _i4.Future<_i2.DataState<List<_i5.WeatherEntity>>> getListWeather({
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getListWeather,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValue: _i4.Future<_i2.DataState<List<_i5.WeatherEntity>>>.value(
            _FakeDataState_0<List<_i5.WeatherEntity>>(
          this,
          Invocation.method(
            #getListWeather,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DataState<List<_i5.WeatherEntity>>>.value(
                _FakeDataState_0<List<_i5.WeatherEntity>>(
          this,
          Invocation.method(
            #getListWeather,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
      ) as _i4.Future<_i2.DataState<List<_i5.WeatherEntity>>>);

  @override
  _i4.Future<_i2.DataState<_i5.WeatherEntity>> getYesterdayWeather({
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getYesterdayWeather,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValue: _i4.Future<_i2.DataState<_i5.WeatherEntity>>.value(
            _FakeDataState_0<_i5.WeatherEntity>(
          this,
          Invocation.method(
            #getYesterdayWeather,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DataState<_i5.WeatherEntity>>.value(
                _FakeDataState_0<_i5.WeatherEntity>(
          this,
          Invocation.method(
            #getYesterdayWeather,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
      ) as _i4.Future<_i2.DataState<_i5.WeatherEntity>>);

  @override
  _i4.Future<_i2.DataState<String>> saveWeatherByAreaToLocal(
          {required List<_i6.AreaEntity>? listArea}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWeatherByAreaToLocal,
          [],
          {#listCity: listArea},
        ),
        returnValue:
            _i4.Future<_i2.DataState<String>>.value(_FakeDataState_0<String>(
          this,
          Invocation.method(
            #saveWeatherByAreaToLocal,
            [],
            {#listCity: listArea},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DataState<String>>.value(_FakeDataState_0<String>(
          this,
          Invocation.method(
            #saveWeatherByAreaToLocal,
            [],
            {#listCity: listArea},
          ),
        )),
      ) as _i4.Future<_i2.DataState<String>>);

  @override
  _i4.Future<_i2.DataState<List<_i6.AreaEntity>>>
      getListWeatherByAreaFromLocal() => (super.noSuchMethod(
            Invocation.method(
              #getListWeatherByAreaFromLocal,
              [],
            ),
            returnValue: _i4.Future<_i2.DataState<List<_i6.AreaEntity>>>.value(
                _FakeDataState_0<List<_i6.AreaEntity>>(
              this,
              Invocation.method(
                #getListWeatherByAreaFromLocal,
                [],
              ),
            )),
            returnValueForMissingStub:
                _i4.Future<_i2.DataState<List<_i6.AreaEntity>>>.value(
                    _FakeDataState_0<List<_i6.AreaEntity>>(
              this,
              Invocation.method(
                #getListWeatherByAreaFromLocal,
                [],
              ),
            )),
          ) as _i4.Future<_i2.DataState<List<_i6.AreaEntity>>>);

  @override
  _i4.Future<_i2.DataState<String>> addWeatherByAreaToLocal(
          {required _i6.AreaEntity? areaEntity}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWeatherByAreaToLocal,
          [],
          {#cityEntity: areaEntity},
        ),
        returnValue:
            _i4.Future<_i2.DataState<String>>.value(_FakeDataState_0<String>(
          this,
          Invocation.method(
            #addWeatherByAreaToLocal,
            [],
            {#cityEntity: areaEntity},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DataState<String>>.value(_FakeDataState_0<String>(
          this,
          Invocation.method(
            #addWeatherByAreaToLocal,
            [],
            {#cityEntity: areaEntity},
          ),
        )),
      ) as _i4.Future<_i2.DataState<String>>);
}
